-- MySQL Script generated by MySQL Workbench
-- 09/25/14 16:03:47
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prueba` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `prueba` ;

-- -----------------------------------------------------
-- Table `prueba`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`rol` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `idRol` INT NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `email` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_rol_idrol_idx` (`idRol` ASC),
  CONSTRAINT `fk_usuario_rol_idrol`
    FOREIGN KEY (`idRol`)
    REFERENCES `prueba`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `shortcut` VARCHAR(45) NULL,
  `icon` VARCHAR(45) NULL,
  `parent` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba`.`access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`access` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idRol` INT NOT NULL,
  `idMenu` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_access_rol_idrol_idx` (`idRol` ASC),
  INDEX `fk_access_menu_idmenu_idx` (`idMenu` ASC),
  CONSTRAINT `fk_access_rol_idrol`
    FOREIGN KEY (`idRol`)
    REFERENCES `prueba`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_access_menu_idmenu`
    FOREIGN KEY (`idMenu`)
    REFERENCES `prueba`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prueba`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prueba`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `population` INT NULL,
  `region` VARCHAR(100) NULL,
  `area` INT NULL,
  `alpha2Code` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
